import type { Difficulty } from "@prisma/client";

export interface CodingProblemSeed {
  title: string;
  slug: string;
  description: string;
  difficulty: Difficulty;
  topic: string;
  fnPython: string;
  fnJs: string;
  fnJava: string;
  testCases: { input: string; expectedOutput: string }[];
  solution: string;
  timeLimit: number;
}

function starter(fnPy: string, fnJs: string, fnJava: string) {
  return {
    python: `def ${fnPy}():\n    # Your code here\n    pass`,
    javascript: `function ${fnJs}() {\n  // Your code here\n}`,
    java: `class Solution {\n    public void ${fnJava}() {\n        // Your code here\n    }\n}`,
    cpp: `class Solution {\npublic:\n    void ${fnJava}() {\n        // Your code here\n    }\n};`,
  };
}

function withStarter(
  p: Omit<CodingProblemSeed, "starterCode"> & { starterCode?: Record<string, string> },
): CodingProblemSeed & { starterCode: Record<string, string> } {
  return {
    ...p,
    starterCode:
      p.starterCode ??
      (() => {
        const base = starter(p.fnPython, p.fnJs, p.fnJava);
        const sigs: Record<string, string> = {
          python: base.python.replace("()", "(...)"),
          javascript: base.javascript.replace("()", "(...)"),
          java: base.java,
          cpp: base.cpp,
        };
        return sigs;
      })(),
  };
}

/** 50 interview-style coding problems for seeding. */
export const CODING_PROBLEMS: (CodingProblemSeed & { starterCode: Record<string, string> })[] = [
  withStarter({
    title: "Two Sum",
    slug: "two-sum",
    description:
      "Given an array of integers `nums` and an integer `target`, return indices of the two numbers that add up to `target`.\n\nYou may assume exactly one solution exists.",
    difficulty: "EASY",
    topic: "Arrays",
    fnPython: "two_sum",
    fnJs: "twoSum",
    fnJava: "twoSum",
    starterCode: {
      python: "def two_sum(nums, target):\n    # Your code here\n    pass",
      javascript: "function twoSum(nums, target) {\n  // Your code here\n}",
      java: "class Solution {\n    public int[] twoSum(int[] nums, int target) {\n        return new int[]{};\n    }\n}",
      cpp: "class Solution {\npublic:\n    vector<int> twoSum(vector<int>& nums, int target) {\n        return {};\n    }\n};",
    },
    testCases: [
      { input: "[2,7,11,15], 9", expectedOutput: "[0,1]" },
      { input: "[3,2,4], 6", expectedOutput: "[1,2]" },
    ],
    solution: "Hash map of complements.",
    timeLimit: 30,
  }),
  withStarter({
    title: "Valid Parentheses",
    slug: "valid-parentheses",
    description: "Given a string containing only `()`, `{}`, and `[]`, determine if it is valid.",
    difficulty: "EASY",
    topic: "Stack",
    fnPython: "is_valid",
    fnJs: "isValid",
    fnJava: "isValid",
    starterCode: {
      python: "def is_valid(s):\n    # Your code here\n    pass",
      javascript: "function isValid(s) {\n  // Your code here\n}",
      java: "class Solution {\n    public boolean isValid(String s) {\n        return false;\n    }\n}",
      cpp: "class Solution {\npublic:\n    bool isValid(string s) {\n        return false;\n    }\n};",
    },
    testCases: [
      { input: '"()"', expectedOutput: "True" },
      { input: '"(]"', expectedOutput: "False" },
      { input: '"{[]}"', expectedOutput: "True" },
    ],
    solution: "Use a stack to match closing brackets.",
    timeLimit: 20,
  }),
  withStarter({
    title: "Best Time to Buy and Sell Stock",
    slug: "best-time-to-buy-sell-stock",
    description: "Return the maximum profit from one buy and one sell. You must buy before you sell.",
    difficulty: "EASY",
    topic: "Arrays",
    fnPython: "max_profit",
    fnJs: "maxProfit",
    fnJava: "maxProfit",
    starterCode: {
      python: "def max_profit(prices):\n    pass",
      javascript: "function maxProfit(prices) {\n  // Your code here\n}",
      java: "class Solution {\n    public int maxProfit(int[] prices) {\n        return 0;\n    }\n}",
      cpp: "class Solution {\npublic:\n    int maxProfit(vector<int>& prices) {\n        return 0;\n    }\n};",
    },
    testCases: [
      { input: "[7,1,5,3,6,4]", expectedOutput: "5" },
      { input: "[7,6,4,3,1]", expectedOutput: "0" },
    ],
    solution: "Track min price and max profit in one pass.",
    timeLimit: 25,
  }),
  withStarter({
    title: "Contains Duplicate",
    slug: "contains-duplicate",
    description: "Return `true` if any value appears at least twice in the array.",
    difficulty: "EASY",
    topic: "Hash Table",
    fnPython: "contains_duplicate",
    fnJs: "containsDuplicate",
    fnJava: "containsDuplicate",
    starterCode: {
      python: "def contains_duplicate(nums):\n    pass",
      javascript: "function containsDuplicate(nums) {\n  // Your code here\n}",
      java: "class Solution {\n    public boolean containsDuplicate(int[] nums) {\n        return false;\n    }\n}",
      cpp: "class Solution {\npublic:\n    bool containsDuplicate(vector<int>& nums) {\n        return false;\n    }\n};",
    },
    testCases: [
      { input: "[1,2,3,1]", expectedOutput: "True" },
      { input: "[1,2,3,4]", expectedOutput: "False" },
    ],
    solution: "Use a set to detect duplicates.",
    timeLimit: 15,
  }),
  withStarter({
    title: "Valid Anagram",
    slug: "valid-anagram",
    description: "Given two strings `s` and `t`, return `true` if `t` is an anagram of `s`.",
    difficulty: "EASY",
    topic: "Strings",
    fnPython: "is_anagram",
    fnJs: "isAnagram",
    fnJava: "isAnagram",
    starterCode: {
      python: 'def is_anagram(s, t):\n    pass',
      javascript: "function isAnagram(s, t) {\n  // Your code here\n}",
      java: "class Solution {\n    public boolean isAnagram(String s, String t) {\n        return false;\n    }\n}",
      cpp: "class Solution {\npublic:\n    bool isAnagram(string s, string t) {\n        return false;\n    }\n};",
    },
    testCases: [
      { input: '"anagram", "nagaram"', expectedOutput: "True" },
      { input: '"rat", "car"', expectedOutput: "False" },
    ],
    solution: "Count character frequencies.",
    timeLimit: 15,
  }),
  withStarter({
    title: "Maximum Subarray",
    slug: "maximum-subarray",
    description: "Find the contiguous subarray with the largest sum and return that sum.",
    difficulty: "EASY",
    topic: "Dynamic Programming",
    fnPython: "max_subarray",
    fnJs: "maxSubArray",
    fnJava: "maxSubArray",
    starterCode: {
      python: "def max_subarray(nums):\n    pass",
      javascript: "function maxSubArray(nums) {\n  // Your code here\n}",
      java: "class Solution {\n    public int maxSubArray(int[] nums) {\n        return 0;\n    }\n}",
      cpp: "class Solution {\npublic:\n    int maxSubArray(vector<int>& nums) {\n        return 0;\n    }\n};",
    },
    testCases: [
      { input: "[-2,1,-3,4,-1,2,1,-5,4]", expectedOutput: "6" },
      { input: "[1]", expectedOutput: "1" },
    ],
    solution: "Kadane's algorithm.",
    timeLimit: 20,
  }),
  withStarter({
    title: "Climbing Stairs",
    slug: "climbing-stairs",
    description: "You can climb 1 or 2 steps. Return how many distinct ways to reach the top.",
    difficulty: "EASY",
    topic: "Dynamic Programming",
    fnPython: "climb_stairs",
    fnJs: "climbStairs",
    fnJava: "climbStairs",
    starterCode: {
      python: "def climb_stairs(n):\n    pass",
      javascript: "function climbStairs(n) {\n  // Your code here\n}",
      java: "class Solution {\n    public int climbStairs(int n) {\n        return 0;\n    }\n}",
      cpp: "class Solution {\npublic:\n    int climbStairs(int n) {\n        return 0;\n    }\n};",
    },
    testCases: [
      { input: "5", expectedOutput: "8" },
      { input: "3", expectedOutput: "3" },
    ],
    solution: "Fibonacci-style DP.",
    timeLimit: 15,
  }),
  withStarter({
    title: "Move Zeroes",
    slug: "move-zeroes",
    description: "Move all zeroes to the end while maintaining relative order of non-zero elements. Return the resulting array.",
    difficulty: "EASY",
    topic: "Two Pointers",
    fnPython: "move_zeroes",
    fnJs: "moveZeroes",
    fnJava: "moveZeroes",
    starterCode: {
      python: "def move_zeroes(nums):\n    pass",
      javascript: "function moveZeroes(nums) {\n  // Your code here\n}",
      java: "class Solution {\n    public int[] moveZeroes(int[] nums) {\n        return nums;\n    }\n}",
      cpp: "class Solution {\npublic:\n    vector<int> moveZeroes(vector<int>& nums) {\n        return {};\n    }\n};",
    },
    testCases: [
      { input: "[0,1,0,3,12]", expectedOutput: "[1, 3, 12, 0, 0]" },
      { input: "[0]", expectedOutput: "[0]" },
    ],
    solution: "Two-pointer swap non-zero values forward.",
    timeLimit: 20,
  }),
  withStarter({
    title: "Reverse String",
    slug: "reverse-string",
    description: "Reverse a list of characters and return the reversed list.",
    difficulty: "EASY",
    topic: "Strings",
    fnPython: "reverse_string",
    fnJs: "reverseString",
    fnJava: "reverseString",
    starterCode: {
      python: 'def reverse_string(chars):\n    pass',
      javascript: "function reverseString(chars) {\n  // Your code here\n}",
      java: "class Solution {\n    public String[] reverseString(String[] chars) {\n        return chars;\n    }\n}",
      cpp: "class Solution {\npublic:\n    vector<char> reverseString(vector<char>& chars) {\n        return {};\n    }\n};",
    },
    testCases: [
      { input: '["h","e","l","l","o"]', expectedOutput: '["o", "l", "l", "e", "h"]' },
      { input: '["H","a","n","n","a","h"]', expectedOutput: '["h", "a", "n", "n", "a", "H"]' },
    ],
    solution: "Two pointers swap from both ends.",
    timeLimit: 15,
  }),
  withStarter({
    title: "Palindrome Number",
    slug: "palindrome-number",
    description: "Return `true` if integer `x` reads the same forward and backward.",
    difficulty: "EASY",
    topic: "Math",
    fnPython: "is_palindrome",
    fnJs: "isPalindrome",
    fnJava: "isPalindrome",
    starterCode: {
      python: "def is_palindrome(x):\n    pass",
      javascript: "function isPalindrome(x) {\n  // Your code here\n}",
      java: "class Solution {\n    public boolean isPalindrome(int x) {\n        return false;\n    }\n}",
      cpp: "class Solution {\npublic:\n    bool isPalindrome(int x) {\n        return false;\n    }\n};",
    },
    testCases: [
      { input: "121", expectedOutput: "True" },
      { input: "-121", expectedOutput: "False" },
    ],
    solution: "Reverse half the digits or convert to string.",
    timeLimit: 15,
  }),
  withStarter({
    title: "Roman to Integer",
    slug: "roman-to-integer",
    description: "Convert a Roman numeral string to an integer.",
    difficulty: "EASY",
    topic: "Strings",
    fnPython: "roman_to_int",
    fnJs: "romanToInt",
    fnJava: "romanToInt",
    starterCode: {
      python: 'def roman_to_int(s):\n    pass',
      javascript: "function romanToInt(s) {\n  // Your code here\n}",
      java: "class Solution {\n    public int romanToInt(String s) {\n        return 0;\n    }\n}",
      cpp: "class Solution {\npublic:\n    int romanToInt(string s) {\n        return 0;\n    }\n};",
    },
    testCases: [
      { input: '"MCMXCIV"', expectedOutput: "1994" },
      { input: '"III"', expectedOutput: "3" },
    ],
    solution: "Map symbols and handle subtractive pairs.",
    timeLimit: 20,
  }),
  withStarter({
    title: "Single Number",
    slug: "single-number",
    description: "Every element appears twice except one. Find that single one.",
    difficulty: "EASY",
    topic: "Bit Manipulation",
    fnPython: "single_number",
    fnJs: "singleNumber",
    fnJava: "singleNumber",
    starterCode: {
      python: "def single_number(nums):\n    pass",
      javascript: "function singleNumber(nums) {\n  // Your code here\n}",
      java: "class Solution {\n    public int singleNumber(int[] nums) {\n        return 0;\n    }\n}",
      cpp: "class Solution {\npublic:\n    int singleNumber(vector<int>& nums) {\n        return 0;\n    }\n};",
    },
    testCases: [
      { input: "[4,1,2,1,2]", expectedOutput: "4" },
      { input: "[1]", expectedOutput: "1" },
    ],
    solution: "XOR all numbers together.",
    timeLimit: 15,
  }),
  withStarter({
    title: "Missing Number",
    slug: "missing-number",
    description: "Array contains `n` distinct numbers in `[0, n]`. Find the missing number.",
    difficulty: "EASY",
    topic: "Arrays",
    fnPython: "missing_number",
    fnJs: "missingNumber",
    fnJava: "missingNumber",
    starterCode: {
      python: "def missing_number(nums):\n    pass",
      javascript: "function missingNumber(nums) {\n  // Your code here\n}",
      java: "class Solution {\n    public int missingNumber(int[] nums) {\n        return 0;\n    }\n}",
      cpp: "class Solution {\npublic:\n    int missingNumber(vector<int>& nums) {\n        return 0;\n    }\n};",
    },
    testCases: [
      { input: "[3,0,1]", expectedOutput: "2" },
      { input: "[0,1]", expectedOutput: "2" },
    ],
    solution: "Sum formula or XOR trick.",
    timeLimit: 15,
  }),
  withStarter({
    title: "Plus One",
    slug: "plus-one",
    description: "Increment a large integer represented as an array of digits.",
    difficulty: "EASY",
    topic: "Arrays",
    fnPython: "plus_one",
    fnJs: "plusOne",
    fnJava: "plusOne",
    starterCode: {
      python: "def plus_one(digits):\n    pass",
      javascript: "function plusOne(digits) {\n  // Your code here\n}",
      java: "class Solution {\n    public int[] plusOne(int[] digits) {\n        return digits;\n    }\n}",
      cpp: "class Solution {\npublic:\n    vector<int> plusOne(vector<int>& digits) {\n        return {};\n    }\n};",
    },
    testCases: [
      { input: "[1,2,3]", expectedOutput: "[1, 2, 4]" },
      { input: "[9]", expectedOutput: "[1, 0]" },
    ],
    solution: "Handle carry from the right.",
    timeLimit: 15,
  }),
  withStarter({
    title: "Happy Number",
    slug: "happy-number",
    description: "Replace n with sum of squares of digits until it equals 1 (happy) or loops (not happy).",
    difficulty: "EASY",
    topic: "Math",
    fnPython: "is_happy",
    fnJs: "isHappy",
    fnJava: "isHappy",
    starterCode: {
      python: "def is_happy(n):\n    pass",
      javascript: "function isHappy(n) {\n  // Your code here\n}",
      java: "class Solution {\n    public boolean isHappy(int n) {\n        return false;\n    }\n}",
      cpp: "class Solution {\npublic:\n    bool isHappy(int n) {\n        return false;\n    }\n};",
    },
    testCases: [
      { input: "19", expectedOutput: "True" },
      { input: "2", expectedOutput: "False" },
    ],
    solution: "Floyd cycle detection on digit-square sum.",
    timeLimit: 20,
  }),
  withStarter({
    title: "Remove Duplicates from Sorted Array",
    slug: "remove-duplicates",
    description: "Remove duplicates in-place from sorted array. Return the new length.",
    difficulty: "EASY",
    topic: "Two Pointers",
    fnPython: "remove_duplicates",
    fnJs: "removeDuplicates",
    fnJava: "removeDuplicates",
    starterCode: {
      python: "def remove_duplicates(nums):\n    pass",
      javascript: "function removeDuplicates(nums) {\n  // Your code here\n}",
      java: "class Solution {\n    public int removeDuplicates(int[] nums) {\n        return 0;\n    }\n}",
      cpp: "class Solution {\npublic:\n    int removeDuplicates(vector<int>& nums) {\n        return 0;\n    }\n};",
    },
    testCases: [
      { input: "[1,1,2]", expectedOutput: "2" },
      { input: "[0,0,1,1,1,2,2,3,3,4]", expectedOutput: "5" },
    ],
    solution: "Slow/fast pointer overwrite unique values.",
    timeLimit: 20,
  }),
  withStarter({
    title: "Sqrt(x)",
    slug: "sqrt-x",
    description: "Return the integer square root of non-negative `x`.",
    difficulty: "EASY",
    topic: "Binary Search",
    fnPython: "my_sqrt",
    fnJs: "mySqrt",
    fnJava: "mySqrt",
    starterCode: {
      python: "def my_sqrt(x):\n    pass",
      javascript: "function mySqrt(x) {\n  // Your code here\n}",
      java: "class Solution {\n    public int mySqrt(int x) {\n        return 0;\n    }\n}",
      cpp: "class Solution {\npublic:\n    int mySqrt(int x) {\n        return 0;\n    }\n};",
    },
    testCases: [
      { input: "8", expectedOutput: "2" },
      { input: "16", expectedOutput: "4" },
    ],
    solution: "Binary search on answer range.",
    timeLimit: 15,
  }),
  withStarter({
    title: "Merge Intervals",
    slug: "merge-intervals",
    description: "Merge all overlapping intervals.",
    difficulty: "MEDIUM",
    topic: "Sorting",
    fnPython: "merge",
    fnJs: "merge",
    fnJava: "merge",
    starterCode: {
      python: "def merge(intervals):\n    pass",
      javascript: "function merge(intervals) {\n  // Your code here\n}",
      java: "class Solution {\n    public int[][] merge(int[][] intervals) {\n        return new int[][]{};\n    }\n}",
      cpp: "class Solution {\npublic:\n    vector<vector<int>> merge(vector<vector<int>>& intervals) {\n        return {};\n    }\n};",
    },
    testCases: [
      { input: "[[1,3],[2,6],[8,10],[15,18]]", expectedOutput: "[[1, 6], [8, 10], [15, 18]]" },
    ],
    solution: "Sort by start, merge overlapping.",
    timeLimit: 30,
  }),
  withStarter({
    title: "Longest Substring Without Repeating Characters",
    slug: "longest-substring",
    description: "Return the length of the longest substring without repeating characters.",
    difficulty: "MEDIUM",
    topic: "Sliding Window",
    fnPython: "length_of_longest_substring",
    fnJs: "lengthOfLongestSubstring",
    fnJava: "lengthOfLongestSubstring",
    starterCode: {
      python: 'def length_of_longest_substring(s):\n    pass',
      javascript: "function lengthOfLongestSubstring(s) {\n  // Your code here\n}",
      java: "class Solution {\n    public int lengthOfLongestSubstring(String s) {\n        return 0;\n    }\n}",
      cpp: "class Solution {\npublic:\n    int lengthOfLongestSubstring(string s) {\n        return 0;\n    }\n};",
    },
    testCases: [
      { input: '"abcabcbb"', expectedOutput: "3" },
      { input: '"bbbbb"', expectedOutput: "1" },
    ],
    solution: "Sliding window with last-seen map.",
    timeLimit: 25,
  }),
  withStarter({
    title: "Product of Array Except Self",
    slug: "product-except-self",
    description: "Return an array where each element is the product of all other elements (no division).",
    difficulty: "MEDIUM",
    topic: "Arrays",
    fnPython: "product_except_self",
    fnJs: "productExceptSelf",
    fnJava: "productExceptSelf",
    starterCode: {
      python: "def product_except_self(nums):\n    pass",
      javascript: "function productExceptSelf(nums) {\n  // Your code here\n}",
      java: "class Solution {\n    public int[] productExceptSelf(int[] nums) {\n        return new int[]{};\n    }\n}",
      cpp: "class Solution {\npublic:\n    vector<int> productExceptSelf(vector<int>& nums) {\n        return {};\n    }\n};",
    },
    testCases: [
      { input: "[1,2,3,4]", expectedOutput: "[24, 12, 8, 6]" },
      { input: "[-1,1,0,-3,3]", expectedOutput: "[0, 0, 9, 0, 0]" },
    ],
    solution: "Prefix and suffix products.",
    timeLimit: 25,
  }),
  withStarter({
    title: "Container With Most Water",
    slug: "container-with-most-water",
    description: "Find two lines that together with the x-axis form a container holding the most water.",
    difficulty: "MEDIUM",
    topic: "Two Pointers",
    fnPython: "max_area",
    fnJs: "maxArea",
    fnJava: "maxArea",
    starterCode: {
      python: "def max_area(height):\n    pass",
      javascript: "function maxArea(height) {\n  // Your code here\n}",
      java: "class Solution {\n    public int maxArea(int[] height) {\n        return 0;\n    }\n}",
      cpp: "class Solution {\npublic:\n    int maxArea(vector<int>& height) {\n        return 0;\n    }\n};",
    },
    testCases: [
      { input: "[1,8,6,2,5,4,8,3,7]", expectedOutput: "49" },
      { input: "[1,1]", expectedOutput: "1" },
    ],
    solution: "Two pointers move inward.",
    timeLimit: 25,
  }),
  withStarter({
    title: "3Sum",
    slug: "three-sum",
    description: "Return all unique triplets that sum to zero.",
    difficulty: "MEDIUM",
    topic: "Arrays",
    fnPython: "three_sum",
    fnJs: "threeSum",
    fnJava: "threeSum",
    starterCode: {
      python: "def three_sum(nums):\n    pass",
      javascript: "function threeSum(nums) {\n  // Your code here\n}",
      java: "class Solution {\n    public List<List<Integer>> threeSum(int[] nums) {\n        return new ArrayList<>();\n    }\n}",
      cpp: "class Solution {\npublic:\n    vector<vector<int>> threeSum(vector<int>& nums) {\n        return {};\n    }\n};",
    },
    testCases: [
      { input: "[-1,0,1,2,-1,-4]", expectedOutput: "[[-1, -1, 2], [-1, 0, 1]]" },
      { input: "[0,1,1]", expectedOutput: "[]" },
    ],
    solution: "Sort, fix one index, two-pointer scan.",
    timeLimit: 30,
  }),
  withStarter({
    title: "Coin Change",
    slug: "coin-change",
    description: "Return the fewest number of coins needed to make up amount, or -1 if impossible.",
    difficulty: "MEDIUM",
    topic: "Dynamic Programming",
    fnPython: "coin_change",
    fnJs: "coinChange",
    fnJava: "coinChange",
    starterCode: {
      python: "def coin_change(coins, amount):\n    pass",
      javascript: "function coinChange(coins, amount) {\n  // Your code here\n}",
      java: "class Solution {\n    public int coinChange(int[] coins, int amount) {\n        return -1;\n    }\n}",
      cpp: "class Solution {\npublic:\n    int coinChange(vector<int>& coins, int amount) {\n        return -1;\n    }\n};",
    },
    testCases: [
      { input: "[1,2,5], 11", expectedOutput: "3" },
      { input: "[2], 3", expectedOutput: "-1" },
    ],
    solution: "Bottom-up DP over amounts.",
    timeLimit: 30,
  }),
  withStarter({
    title: "House Robber",
    slug: "house-robber",
    description: "Maximize money robbed without robbing two adjacent houses.",
    difficulty: "MEDIUM",
    topic: "Dynamic Programming",
    fnPython: "rob",
    fnJs: "rob",
    fnJava: "rob",
    starterCode: {
      python: "def rob(nums):\n    pass",
      javascript: "function rob(nums) {\n  // Your code here\n}",
      java: "class Solution {\n    public int rob(int[] nums) {\n        return 0;\n    }\n}",
      cpp: "class Solution {\npublic:\n    int rob(vector<int>& nums) {\n        return 0;\n    }\n};",
    },
    testCases: [
      { input: "[1,2,3,1]", expectedOutput: "4" },
      { input: "[2,7,9,3,1]", expectedOutput: "12" },
    ],
    solution: "DP: rob current + skip previous.",
    timeLimit: 25,
  }),
  withStarter({
    title: "Unique Paths",
    slug: "unique-paths",
    description: "Robot on m×n grid can only move right or down. How many unique paths to bottom-right?",
    difficulty: "MEDIUM",
    topic: "Dynamic Programming",
    fnPython: "unique_paths",
    fnJs: "uniquePaths",
    fnJava: "uniquePaths",
    starterCode: {
      python: "def unique_paths(m, n):\n    pass",
      javascript: "function uniquePaths(m, n) {\n  // Your code here\n}",
      java: "class Solution {\n    public int uniquePaths(int m, int n) {\n        return 0;\n    }\n}",
      cpp: "class Solution {\npublic:\n    int uniquePaths(int m, int n) {\n        return 0;\n    }\n};",
    },
    testCases: [
      { input: "3, 7", expectedOutput: "28" },
      { input: "3, 2", expectedOutput: "3" },
    ],
    solution: "DP table or combinatorics.",
    timeLimit: 20,
  }),
  withStarter({
    title: "Decode Ways",
    slug: "decode-ways",
    description: 'Count ways to decode a string of digits (1-26 maps to A-Z).',
    difficulty: "MEDIUM",
    topic: "Dynamic Programming",
    fnPython: "num_decodings",
    fnJs: "numDecodings",
    fnJava: "numDecodings",
    starterCode: {
      python: 'def num_decodings(s):\n    pass',
      javascript: "function numDecodings(s) {\n  // Your code here\n}",
      java: "class Solution {\n    public int numDecodings(String s) {\n        return 0;\n    }\n}",
      cpp: "class Solution {\npublic:\n    int numDecodings(string s) {\n        return 0;\n    }\n};",
    },
    testCases: [
      { input: '"12"', expectedOutput: "2" },
      { input: '"226"', expectedOutput: "3" },
    ],
    solution: "DP with single and double digit transitions.",
    timeLimit: 25,
  }),
  withStarter({
    title: "Jump Game",
    slug: "jump-game",
    description: "Return `true` if you can reach the last index starting at index 0.",
    difficulty: "MEDIUM",
    topic: "Greedy",
    fnPython: "can_jump",
    fnJs: "canJump",
    fnJava: "canJump",
    starterCode: {
      python: "def can_jump(nums):\n    pass",
      javascript: "function canJump(nums) {\n  // Your code here\n}",
      java: "class Solution {\n    public boolean canJump(int[] nums) {\n        return false;\n    }\n}",
      cpp: "class Solution {\npublic:\n    bool canJump(vector<int>& nums) {\n        return false;\n    }\n};",
    },
    testCases: [
      { input: "[2,3,1,1,4]", expectedOutput: "True" },
      { input: "[3,2,1,0,4]", expectedOutput: "False" },
    ],
    solution: "Track farthest reachable index.",
    timeLimit: 20,
  }),
  withStarter({
    title: "Daily Temperatures",
    slug: "daily-temperatures",
    description: "For each day, return how many days until a warmer temperature (0 if none).",
    difficulty: "MEDIUM",
    topic: "Stack",
    fnPython: "daily_temperatures",
    fnJs: "dailyTemperatures",
    fnJava: "dailyTemperatures",
    starterCode: {
      python: "def daily_temperatures(temps):\n    pass",
      javascript: "function dailyTemperatures(temps) {\n  // Your code here\n}",
      java: "class Solution {\n    public int[] dailyTemperatures(int[] temps) {\n        return new int[]{};\n    }\n}",
      cpp: "class Solution {\npublic:\n    vector<int> dailyTemperatures(vector<int>& temps) {\n        return {};\n    }\n};",
    },
    testCases: [
      { input: "[73,74,75,71,69,72,76,73]", expectedOutput: "[1, 1, 4, 2, 1, 1, 0, 0]" },
    ],
    solution: "Monotonic decreasing stack of indices.",
    timeLimit: 25,
  }),
  withStarter({
    title: "Subarray Sum Equals K",
    slug: "subarray-sum-equals-k",
    description: "Return the total number of continuous subarrays whose sum equals `k`.",
    difficulty: "MEDIUM",
    topic: "Hash Table",
    fnPython: "subarray_sum",
    fnJs: "subarraySum",
    fnJava: "subarraySum",
    starterCode: {
      python: "def subarray_sum(nums, k):\n    pass",
      javascript: "function subarraySum(nums, k) {\n  // Your code here\n}",
      java: "class Solution {\n    public int subarraySum(int[] nums, int k) {\n        return 0;\n    }\n}",
      cpp: "class Solution {\npublic:\n    int subarraySum(vector<int>& nums, int k) {\n        return 0;\n    }\n};",
    },
    testCases: [
      { input: "[1,1,1], 2", expectedOutput: "2" },
      { input: "[1,2,3], 3", expectedOutput: "2" },
    ],
    solution: "Prefix sum with hash map counts.",
    timeLimit: 25,
  }),
  withStarter({
    title: "Find All Anagrams in a String",
    slug: "find-anagrams",
    description: "Return start indices of all anagrams of `p` in `s`.",
    difficulty: "MEDIUM",
    topic: "Sliding Window",
    fnPython: "find_anagrams",
    fnJs: "findAnagrams",
    fnJava: "findAnagrams",
    starterCode: {
      python: 'def find_anagrams(s, p):\n    pass',
      javascript: "function findAnagrams(s, p) {\n  // Your code here\n}",
      java: "class Solution {\n    public List<Integer> findAnagrams(String s, String p) {\n        return new ArrayList<>();\n    }\n}",
      cpp: "class Solution {\npublic:\n    vector<int> findAnagrams(string s, string p) {\n        return {};\n    }\n};",
    },
    testCases: [
      { input: '"cbaebabacd", "abc"', expectedOutput: "[0, 6]" },
      { input: '"abab", "ab"', expectedOutput: "[0, 1, 2]" },
    ],
    solution: "Fixed-size sliding window with frequency map.",
    timeLimit: 25,
  }),
  withStarter({
    title: "Rotate Array",
    slug: "rotate-array",
    description: "Rotate array to the right by `k` steps. Return the rotated array.",
    difficulty: "MEDIUM",
    topic: "Arrays",
    fnPython: "rotate",
    fnJs: "rotate",
    fnJava: "rotate",
    starterCode: {
      python: "def rotate(nums, k):\n    pass",
      javascript: "function rotate(nums, k) {\n  // Your code here\n}",
      java: "class Solution {\n    public int[] rotate(int[] nums, int k) {\n        return nums;\n    }\n}",
      cpp: "class Solution {\npublic:\n    vector<int> rotate(vector<int>& nums, int k) {\n        return {};\n    }\n};",
    },
    testCases: [
      { input: "[1,2,3,4,5,6,7], 3", expectedOutput: "[5, 6, 7, 1, 2, 3, 4]" },
      { input: "[-1,-100,3,99], 2", expectedOutput: "[3, 99, -1, -100]" },
    ],
    solution: "Reverse segments or use modulo indexing.",
    timeLimit: 25,
  }),
  withStarter({
    title: "Sort Colors",
    slug: "sort-colors",
    description: "Sort array of 0s, 1s, and 2s in-place. Return sorted array.",
    difficulty: "MEDIUM",
    topic: "Arrays",
    fnPython: "sort_colors",
    fnJs: "sortColors",
    fnJava: "sortColors",
    starterCode: {
      python: "def sort_colors(nums):\n    pass",
      javascript: "function sortColors(nums) {\n  // Your code here\n}",
      java: "class Solution {\n    public int[] sortColors(int[] nums) {\n        return nums;\n    }\n}",
      cpp: "class Solution {\npublic:\n    vector<int> sortColors(vector<int>& nums) {\n        return {};\n    }\n};",
    },
    testCases: [
      { input: "[2,0,2,1,1,0]", expectedOutput: "[0, 0, 1, 1, 2, 2]" },
      { input: "[2,0,1]", expectedOutput: "[0, 1, 2]" },
    ],
    solution: "Dutch national flag three-pointer.",
    timeLimit: 20,
  }),
  withStarter({
    title: "Search in Rotated Sorted Array",
    slug: "search-rotated-array",
    description: "Search `target` in a rotated sorted array. Return index or -1.",
    difficulty: "MEDIUM",
    topic: "Binary Search",
    fnPython: "search",
    fnJs: "search",
    fnJava: "search",
    starterCode: {
      python: "def search(nums, target):\n    pass",
      javascript: "function search(nums, target) {\n  // Your code here\n}",
      java: "class Solution {\n    public int search(int[] nums, int target) {\n        return -1;\n    }\n}",
      cpp: "class Solution {\npublic:\n    int search(vector<int>& nums, int target) {\n        return -1;\n    }\n};",
    },
    testCases: [
      { input: "[4,5,6,7,0,1,2], 0", expectedOutput: "4" },
      { input: "[1], 0", expectedOutput: "-1" },
    ],
    solution: "Binary search identifying sorted half.",
    timeLimit: 25,
  }),
  withStarter({
    title: "Kth Largest Element in an Array",
    slug: "kth-largest",
    description: "Find the kth largest element in an unsorted array.",
    difficulty: "MEDIUM",
    topic: "Heap",
    fnPython: "find_kth_largest",
    fnJs: "findKthLargest",
    fnJava: "findKthLargest",
    starterCode: {
      python: "def find_kth_largest(nums, k):\n    pass",
      javascript: "function findKthLargest(nums, k) {\n  // Your code here\n}",
      java: "class Solution {\n    public int findKthLargest(int[] nums, int k) {\n        return 0;\n    }\n}",
      cpp: "class Solution {\npublic:\n    int findKthLargest(vector<int>& nums, int k) {\n        return 0;\n    }\n};",
    },
    testCases: [
      { input: "[3,2,1,5,6,4], 2", expectedOutput: "5" },
      { input: "[3,2,3,1,2,4,5,5,6], 4", expectedOutput: "4" },
    ],
    solution: "Quickselect or min-heap of size k.",
    timeLimit: 25,
  }),
  withStarter({
    title: "Word Break",
    slug: "word-break",
    description: "Return `true` if `s` can be segmented into dictionary words.",
    difficulty: "MEDIUM",
    topic: "Dynamic Programming",
    fnPython: "word_break",
    fnJs: "wordBreak",
    fnJava: "wordBreak",
    starterCode: {
      python: 'def word_break(s, word_dict):\n    pass',
      javascript: "function wordBreak(s, wordDict) {\n  // Your code here\n}",
      java: "class Solution {\n    public boolean wordBreak(String s, List<String> wordDict) {\n        return false;\n    }\n}",
      cpp: "class Solution {\npublic:\n    bool wordBreak(string s, vector<string>& wordDict) {\n        return false;\n    }\n};",
    },
    testCases: [
      { input: '"leetcode", ["leet","code"]', expectedOutput: "True" },
      { input: '"applepenapple", ["apple","pen"]', expectedOutput: "True" },
    ],
    solution: "DP boolean reachable prefixes.",
    timeLimit: 25,
  }),
  withStarter({
    title: "Spiral Matrix",
    slug: "spiral-matrix",
    description: "Return all elements of the matrix in spiral order.",
    difficulty: "MEDIUM",
    topic: "Arrays",
    fnPython: "spiral_order",
    fnJs: "spiralOrder",
    fnJava: "spiralOrder",
    starterCode: {
      python: "def spiral_order(matrix):\n    pass",
      javascript: "function spiralOrder(matrix) {\n  // Your code here\n}",
      java: "class Solution {\n    public List<Integer> spiralOrder(int[][] matrix) {\n        return new ArrayList<>();\n    }\n}",
      cpp: "class Solution {\npublic:\n    vector<int> spiralOrder(vector<vector<int>>& matrix) {\n        return {};\n    }\n};",
    },
    testCases: [
      { input: "[[1,2,3],[4,5,6],[7,8,9]]", expectedOutput: "[1, 2, 3, 6, 9, 8, 7, 4, 5]" },
      { input: "[[1,2,3,4],[5,6,7,8],[9,10,11,12]]", expectedOutput: "[1, 2, 3, 4, 8, 12, 11, 10, 9, 5, 6, 7]" },
    ],
    solution: "Shrink boundaries top/right/bottom/left.",
    timeLimit: 25,
  }),
  withStarter({
    title: "Longest Increasing Subsequence",
    slug: "longest-increasing-subsequence",
    description: "Return the length of the longest strictly increasing subsequence.",
    difficulty: "MEDIUM",
    topic: "Dynamic Programming",
    fnPython: "length_of_lis",
    fnJs: "lengthOfLIS",
    fnJava: "lengthOfLIS",
    starterCode: {
      python: "def length_of_lis(nums):\n    pass",
      javascript: "function lengthOfLIS(nums) {\n  // Your code here\n}",
      java: "class Solution {\n    public int lengthOfLIS(int[] nums) {\n        return 0;\n    }\n}",
      cpp: "class Solution {\npublic:\n    int lengthOfLIS(vector<int>& nums) {\n        return 0;\n    }\n};",
    },
    testCases: [
      { input: "[10,9,2,5,3,7,101,18]", expectedOutput: "4" },
      { input: "[0,1,0,3,2,3]", expectedOutput: "4" },
    ],
    solution: "Patience sorting / binary search on tails.",
    timeLimit: 30,
  }),
  withStarter({
    title: "Gas Station",
    slug: "gas-station",
    description: "Circular route with gas stations. Return starting index if circuit possible, else -1.",
    difficulty: "MEDIUM",
    topic: "Greedy",
    fnPython: "can_complete_circuit",
    fnJs: "canCompleteCircuit",
    fnJava: "canCompleteCircuit",
    starterCode: {
      python: "def can_complete_circuit(gas, cost):\n    pass",
      javascript: "function canCompleteCircuit(gas, cost) {\n  // Your code here\n}",
      java: "class Solution {\n    public int canCompleteCircuit(int[] gas, int[] cost) {\n        return -1;\n    }\n}",
      cpp: "class Solution {\npublic:\n    int canCompleteCircuit(vector<int>& gas, vector<int>& cost) {\n        return -1;\n    }\n};",
    },
    testCases: [
      { input: "[1,2,3,4,5], [3,4,5,1,2]", expectedOutput: "3" },
      { input: "[2,3,4], [3,4,3]", expectedOutput: "-1" },
    ],
    solution: "Track total and current tank deficit.",
    timeLimit: 25,
  }),
  withStarter({
    title: "Meeting Rooms II",
    slug: "meeting-rooms-ii",
    description: "Return the minimum number of conference rooms required.",
    difficulty: "MEDIUM",
    topic: "Heap",
    fnPython: "min_meeting_rooms",
    fnJs: "minMeetingRooms",
    fnJava: "minMeetingRooms",
    starterCode: {
      python: "def min_meeting_rooms(intervals):\n    pass",
      javascript: "function minMeetingRooms(intervals) {\n  // Your code here\n}",
      java: "class Solution {\n    public int minMeetingRooms(int[][] intervals) {\n        return 0;\n    }\n}",
      cpp: "class Solution {\npublic:\n    int minMeetingRooms(vector<vector<int>>& intervals) {\n        return 0;\n    }\n};",
    },
    testCases: [
      { input: "[[0,30],[5,10],[15,20]]", expectedOutput: "2" },
      { input: "[[7,10],[2,4]]", expectedOutput: "1" },
    ],
    solution: "Sort starts, min-heap of end times.",
    timeLimit: 25,
  }),
  withStarter({
    title: "Binary Tree Level Order Traversal",
    slug: "binary-tree-level-order",
    description:
      "Given a level-order array (None for missing nodes), return values grouped by level.",
    difficulty: "MEDIUM",
    topic: "Trees",
    fnPython: "level_order",
    fnJs: "levelOrder",
    fnJava: "levelOrder",
    starterCode: {
      python:
        "class TreeNode:\n    def __init__(self, val=0, left=None, right=None):\n        self.val = val\n        self.left = left\n        self.right = right\n\ndef build_tree(arr):\n    if not arr:\n        return None\n    nodes = [TreeNode(x) if x is not None else None for x in arr]\n    kids = nodes[::-1]\n    root = kids.pop()\n    for node in nodes:\n        if node:\n            if kids: node.left = kids.pop()\n            if kids: node.right = kids.pop()\n    return root\n\ndef level_order(root):\n    pass",
      javascript:
        "function TreeNode(val, left, right) { this.val = val ?? 0; this.left = left ?? null; this.right = right ?? null; }\nfunction levelOrder(root) {\n  // Your code here\n}",
      java: "class Solution {\n    public List<List<Integer>> levelOrder(TreeNode root) {\n        return new ArrayList<>();\n    }\n}",
      cpp: "class Solution {\npublic:\n    vector<vector<int>> levelOrder(TreeNode* root) {\n        return {};\n    }\n};",
    },
    testCases: [
      { input: "build_tree([3,9,20,None,None,15,7])", expectedOutput: "[[3], [9, 20], [15, 7]]" },
    ],
    solution: "BFS with a queue.",
    timeLimit: 25,
  }),
  withStarter({
    title: "Number of Islands",
    slug: "number-of-islands",
    description: "Count islands of `1` in a 2D grid surrounded by water `0`.",
    difficulty: "MEDIUM",
    topic: "Graph",
    fnPython: "num_islands",
    fnJs: "numIslands",
    fnJava: "numIslands",
    starterCode: {
      python: "def num_islands(grid):\n    pass",
      javascript: "function numIslands(grid) {\n  // Your code here\n}",
      java: "class Solution {\n    public int numIslands(char[][] grid) {\n        return 0;\n    }\n}",
      cpp: "class Solution {\npublic:\n    int numIslands(vector<vector<char>>& grid) {\n        return 0;\n    }\n};",
    },
    testCases: [
      {
        input: '[["1","1","1","1","0"],["1","1","0","1","0"],["1","1","0","0","0"],["0","0","0","0","0"]]',
        expectedOutput: "1",
      },
      { input: '[["1","1","0","0","0"],["1","1","0","0","0"],["0","0","1","1","1"]]', expectedOutput: "3" },
    ],
    solution: "DFS/BFS flood fill.",
    timeLimit: 30,
  }),
  withStarter({
    title: "Course Schedule",
    slug: "course-schedule",
    description: "Return `true` if you can finish all courses given prerequisites.",
    difficulty: "MEDIUM",
    topic: "Graph",
    fnPython: "can_finish",
    fnJs: "canFinish",
    fnJava: "canFinish",
    starterCode: {
      python: "def can_finish(num_courses, prerequisites):\n    pass",
      javascript: "function canFinish(numCourses, prerequisites) {\n  // Your code here\n}",
      java: "class Solution {\n    public boolean canFinish(int numCourses, int[][] prerequisites) {\n        return false;\n    }\n}",
      cpp: "class Solution {\npublic:\n    bool canFinish(int numCourses, vector<vector<int>>& prerequisites) {\n        return false;\n    }\n};",
    },
    testCases: [
      { input: "2, [[1,0]]", expectedOutput: "True" },
      { input: "2, [[1,0],[0,1]]", expectedOutput: "False" },
    ],
    solution: "Topological sort / cycle detection.",
    timeLimit: 25,
  }),
  withStarter({
    title: "Word Ladder",
    slug: "word-ladder",
    description: "Return length of shortest transformation sequence from begin to end word.",
    difficulty: "HARD",
    topic: "Graph",
    fnPython: "ladder_length",
    fnJs: "ladderLength",
    fnJava: "ladderLength",
    starterCode: {
      python: 'def ladder_length(begin_word, end_word, word_list):\n    pass',
      javascript: "function ladderLength(beginWord, endWord, wordList) {\n  // Your code here\n}",
      java: "class Solution {\n    public int ladderLength(String beginWord, String endWord, List<String> wordList) {\n        return 0;\n    }\n}",
      cpp: "class Solution {\npublic:\n    int ladderLength(string beginWord, string endWord, vector<string>& wordList) {\n        return 0;\n    }\n};",
    },
    testCases: [
      { input: '"hit", "cog", ["hot","dot","dog","lot","log","cog"]', expectedOutput: "5" },
      { input: '"hit", "cog", ["hot","dot","dog","lot","log"]', expectedOutput: "0" },
    ],
    solution: "BFS on word graph.",
    timeLimit: 35,
  }),
  withStarter({
    title: "Trapping Rain Water",
    slug: "trapping-rain-water",
    description: "Compute how much water can be trapped after raining.",
    difficulty: "HARD",
    topic: "Arrays",
    fnPython: "trap",
    fnJs: "trap",
    fnJava: "trap",
    starterCode: {
      python: "def trap(height):\n    pass",
      javascript: "function trap(height) {\n  // Your code here\n}",
      java: "class Solution {\n    public int trap(int[] height) {\n        return 0;\n    }\n}",
      cpp: "class Solution {\npublic:\n    int trap(vector<int>& height) {\n        return 0;\n    }\n};",
    },
    testCases: [
      { input: "[0,1,0,2,1,0,1,3,2,1,2,1]", expectedOutput: "6" },
      { input: "[4,2,0,3,2,5]", expectedOutput: "9" },
    ],
    solution: "Two pointers or prefix max arrays.",
    timeLimit: 30,
  }),
  withStarter({
    title: "Sliding Window Maximum",
    slug: "sliding-window-maximum",
    description: "Return max value in each sliding window of size `k`.",
    difficulty: "HARD",
    topic: "Sliding Window",
    fnPython: "max_sliding_window",
    fnJs: "maxSlidingWindow",
    fnJava: "maxSlidingWindow",
    starterCode: {
      python: "def max_sliding_window(nums, k):\n    pass",
      javascript: "function maxSlidingWindow(nums, k) {\n  // Your code here\n}",
      java: "class Solution {\n    public int[] maxSlidingWindow(int[] nums, int k) {\n        return new int[]{};\n    }\n}",
      cpp: "class Solution {\npublic:\n    vector<int> maxSlidingWindow(vector<int>& nums, int k) {\n        return {};\n    }\n};",
    },
    testCases: [
      { input: "[1,3,-1,-3,5,3,6,7], 3", expectedOutput: "[3, 3, 5, 5, 6, 7]" },
      { input: "[1], 1", expectedOutput: "[1]" },
    ],
    solution: "Monotonic deque of indices.",
    timeLimit: 30,
  }),
  withStarter({
    title: "Edit Distance",
    slug: "edit-distance",
    description: "Minimum operations (insert, delete, replace) to convert word1 to word2.",
    difficulty: "HARD",
    topic: "Dynamic Programming",
    fnPython: "min_distance",
    fnJs: "minDistance",
    fnJava: "minDistance",
    starterCode: {
      python: 'def min_distance(word1, word2):\n    pass',
      javascript: "function minDistance(word1, word2) {\n  // Your code here\n}",
      java: "class Solution {\n    public int minDistance(String word1, String word2) {\n        return 0;\n    }\n}",
      cpp: "class Solution {\npublic:\n    int minDistance(string word1, string word2) {\n        return 0;\n    }\n};",
    },
    testCases: [
      { input: '"horse", "ros"', expectedOutput: "3" },
      { input: '"intention", "execution"', expectedOutput: "5" },
    ],
    solution: "2D DP on prefixes.",
    timeLimit: 30,
  }),
  withStarter({
    title: "Regular Expression Matching",
    slug: "regex-matching",
    description: "Implement regex matching with `.` and `*` support.",
    difficulty: "HARD",
    topic: "Dynamic Programming",
    fnPython: "is_match",
    fnJs: "isMatch",
    fnJava: "isMatch",
    starterCode: {
      python: 'def is_match(s, p):\n    pass',
      javascript: "function isMatch(s, p) {\n  // Your code here\n}",
      java: "class Solution {\n    public boolean isMatch(String s, String p) {\n        return false;\n    }\n}",
      cpp: "class Solution {\npublic:\n    bool isMatch(string s, string p) {\n        return false;\n    }\n};",
    },
    testCases: [
      { input: '"aa", "a*"', expectedOutput: "True" },
      { input: '"ab", ".*"', expectedOutput: "True" },
    ],
    solution: "DP or recursion with memo on pattern index.",
    timeLimit: 35,
  }),
  withStarter({
    title: "Largest Rectangle in Histogram",
    slug: "largest-rectangle-histogram",
    description: "Return area of the largest rectangle in the histogram.",
    difficulty: "HARD",
    topic: "Stack",
    fnPython: "largest_rectangle_area",
    fnJs: "largestRectangleArea",
    fnJava: "largestRectangleArea",
    starterCode: {
      python: "def largest_rectangle_area(heights):\n    pass",
      javascript: "function largestRectangleArea(heights) {\n  // Your code here\n}",
      java: "class Solution {\n    public int largestRectangleArea(int[] heights) {\n        return 0;\n    }\n}",
      cpp: "class Solution {\npublic:\n    int largestRectangleArea(vector<int>& heights) {\n        return 0;\n    }\n};",
    },
    testCases: [
      { input: "[2,1,5,6,2,3]", expectedOutput: "10" },
      { input: "[2,4]", expectedOutput: "4" },
    ],
    solution: "Monotonic stack of increasing heights.",
    timeLimit: 30,
  }),
  withStarter({
    title: "Minimum Window Substring",
    slug: "min-window-substring",
    description: "Return the smallest window in `s` that contains all characters of `t`.",
    difficulty: "HARD",
    topic: "Sliding Window",
    fnPython: "min_window",
    fnJs: "minWindow",
    fnJava: "minWindow",
    starterCode: {
      python: 'def min_window(s, t):\n    pass',
      javascript: "function minWindow(s, t) {\n  // Your code here\n}",
      java: "class Solution {\n    public String minWindow(String s, String t) {\n        return \"\";\n    }\n}",
      cpp: "class Solution {\npublic:\n    string minWindow(string s, string t) {\n        return \"\";\n    }\n};",
    },
    testCases: [
      { input: '"ADOBECODEBANC", "ABC"', expectedOutput: '"BANC"' },
      { input: '"a", "a"', expectedOutput: '"a"' },
    ],
    solution: "Expand/shrink window with frequency map.",
    timeLimit: 35,
  }),
  withStarter({
    title: "Merge k Sorted Lists",
    slug: "merge-k-lists",
    description: "Merge k sorted linked lists represented as nested arrays. Return merged sorted array.",
    difficulty: "HARD",
    topic: "Heap",
    fnPython: "merge_k_lists",
    fnJs: "mergeKLists",
    fnJava: "mergeKLists",
    starterCode: {
      python: "def merge_k_lists(lists):\n    pass",
      javascript: "function mergeKLists(lists) {\n  // Your code here\n}",
      java: "class Solution {\n    public List<Integer> mergeKLists(List<ListNode> lists) {\n        return new ArrayList<>();\n    }\n}",
      cpp: "class Solution {\npublic:\n    vector<int> mergeKLists(vector<ListNode*>& lists) {\n        return {};\n    }\n};",
    },
    testCases: [
      { input: "[[1,4,5],[1,3,4],[2,6]]", expectedOutput: "[1, 1, 2, 3, 4, 4, 5, 6]" },
      { input: "[]", expectedOutput: "[]" },
    ],
    solution: "Min-heap of list heads.",
    timeLimit: 35,
  }),
  withStarter({
    title: "Serialize and Deserialize Binary Tree",
    slug: "serialize-tree",
    description: "Serialize a level-order tree array to string and deserialize back. Return round-trip array.",
    difficulty: "HARD",
    topic: "Trees",
    fnPython: "serialize_roundtrip",
    fnJs: "serializeRoundtrip",
    fnJava: "serializeRoundtrip",
    starterCode: {
      python:
        "def serialize_roundtrip(arr):\n    # Return the same level-order list after serialize + deserialize\n    pass",
      javascript: "function serializeRoundtrip(arr) {\n  // Your code here\n}",
      java: "class Solution {\n    public List<Integer> serializeRoundtrip(int[] arr) {\n        return new ArrayList<>();\n    }\n}",
      cpp: "class Solution {\npublic:\n    vector<int> serializeRoundtrip(vector<int>& arr) {\n        return {};\n    }\n};",
    },
    testCases: [
      { input: "[1,2,3,None,None,4,5]", expectedOutput: "[1, 2, 3, None, None, 4, 5]" },
    ],
    solution: "BFS encoding with null markers.",
    timeLimit: 35,
  }),
  withStarter({
    title: "N-Queens Count",
    slug: "n-queens",
    description: "Return the number of distinct solutions to the n-queens puzzle.",
    difficulty: "HARD",
    topic: "Backtracking",
    fnPython: "total_n_queens",
    fnJs: "totalNQueens",
    fnJava: "totalNQueens",
    starterCode: {
      python: "def total_n_queens(n):\n    pass",
      javascript: "function totalNQueens(n) {\n  // Your code here\n}",
      java: "class Solution {\n    public int totalNQueens(int n) {\n        return 0;\n    }\n}",
      cpp: "class Solution {\npublic:\n    int totalNQueens(int n) {\n        return 0;\n    }\n};",
    },
    testCases: [
      { input: "4", expectedOutput: "2" },
      { input: "1", expectedOutput: "1" },
    ],
    solution: "Backtracking with column/diagonal sets.",
    timeLimit: 35,
  }),
];

/** Build slug → function name map for the code runner. */
export function buildFunctionNames() {
  const map: Record<string, Record<string, string>> = {};
  for (const p of CODING_PROBLEMS) {
    map[p.slug] = {
      python: p.fnPython,
      javascript: p.fnJs,
      java: p.fnJava,
      cpp: p.fnJava,
    };
  }
  return map;
}
